# Generated by Django 5.2.9 on 2026-07-12 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FastFoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maxsulot narxi: ')),
                ('ingredients', models.TextField(max_length=4000, verbose_name='Tarkibi: ')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='necha dona borr')),
                ('product_image', models.ImageField(upload_to='products/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='products.category')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name="Zakar borishi kk bo'lgan manzil")),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlandi', 'Tasdiqlandi'), ('Tayyorlanmoqda', 'Tayyorlanmoqda'), ('Yo‘lga chiqdi', 'Yo‘lga chiqdi'), ('Yetkazildi', 'Yetkazildi'), ('Bekor qilindi', 'Bekor qilindi'), ('Qaytarildi', 'Qaytarildi')], default='Kutilmoqda', max_length=30)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta (Terminal)'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Karta egasi')),
                ('card_number', models.CharField(blank=True, max_length=19, null=True, verbose_name='Karta raqami')),
                ('card_expiry', models.CharField(blank=True, max_length=5, null=True, verbose_name='Amal qilish muddati')),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True, verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(editable=False, help_text='Sotib olingan vaqtdagi narxi')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.fastfoodproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_list', to='products.fastfoodproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
