# Generated by Django 5.2.9 on 2026-06-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfoodproduct',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='necha dona borr'),
        ),
    ]
