# Generated by Django 5.2.15 on 2026-07-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('payme', 'Payme')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
